name: wireframe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/tempe.jpg
    - assets/dada_ayam.jpg
    - assets/paha_ayam.jpg
    - assets/ikan_nila.jpg
  uses-material-design: true

